language: ruby
rvm:
- 2.1.1
install:
- gem install github-pages html-proofer
before_script:
- git config user.name "Travis-CI"
- git config user.email "noreply@travis-ci.org"
script:
- jekyll build
- git init
- git add .
- git commit -m "Deploy to Github Pages"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - Dev
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/PowerShellConferenceEU/dev.git
  - secure: Xc0hCYj/ONxyB4OXlLnQuB2qsdCXKByZQd7Dt9kHGS0931E6tojd9JqdMKJLpPbV39btL/PPRSp7J6RhUFegi7PYrSBeXB+RN99YTUQENtVPL6MXJ+EpLjkV70xMR++qzHuuUJ0TFVCSXqzxMOTJflMn4hRLhX/l+XLMIZV/n7Nq+XcpSAZuWU5loYASzeFAuXk8Z9nFWs5Fqoy6vbWt8qGm3NDRShLVy1oUCRCeMioCpUC20chdUgsGBXKVj6NN8NZRYfkWQNrITv3A5DECu/T8or8rCvEOyKEqyGwtVNUatX/AnisPOAQRYU6oWrLpiIGIJI8YYxfwnrLATnBjCTfX6aKdTqgVdzo5VruTIaW3v8rPQoQw6zGbi+dhogztc/sbqIdEOyPDD6EUQR5Sa5xm+Yhp+sWHQtbRnx++pMiSSV4uYh3xLyyDavBtUZTbRgJx+z5o6eyR1UUDW9Dd2Oncb9jhRqjOSgbLWL/Z3CnbFCCo3l5WUealrdAdEW3T8aTim+ztfiE9tknI/9Sb89wPpwro7SUNnCqLVfnY3PA0t8np3CjhVLeaVmxfCMbqKTWxc8Nk7PiXM2iuCCzQ8GbD2B7ISrTf26ktSJaoB1UbH+kUbhu1Sr73GlR4E5DVc7aFII6sFZINt+S2P3pxeH7n4aml/dmFkbtUrvGw6o4=
