language: ruby
rvm:
  - 2.1.1

install:
  - pip install --user html5validator
  - gem install github-pages html-proofer
  
script:
  - jekyll build
#  - htmlproof ./_site
#  - html5validator --root ./_site

branches:
  only:
    - Dev

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer